from os import environ

APP_LOGGER_NAME = environ['APP_LOGGER_NAME']
CACHE_PORT = environ['CACHE_PORT']
CACHE_URL = environ['CACHE_URL']
CORE_API_URL = environ['CORE_API_URL']
CORE_API_PORT = environ['CORE_API_PORT']
CORE_API_USER = environ['CORE_API_USER']
CORE_API_PASSWORD = environ['CORE_API_PASSWORD']
NETWORK_API_URL = environ['NETWORK_API_URL']
NETWORK_API_PORT = environ['NETWORK_API_PORT']
NETWORK_API_USER = environ['NETWORK_API_USER']
NETWORK_API_PASSWORD = environ['NETWORK_API_PASSWORD']
